# Generated by Django 4.2.27 on 2025-12-15 16:25

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('icon', models.CharField(default='sun', help_text="Heroicons name (e.g., 'sun', 'bolt', 'wrench')", max_length=50)),
                ('short_description', models.CharField(help_text='Krótki opis wyświetlany na stronie głównej', max_length=200)),
                ('content', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(icon='title', max_length=200, template='services/blocks/heading.html')), ('paragraph', wagtail.blocks.RichTextBlock(icon='doc-full', template='services/blocks/paragraph.html')), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image', template='services/blocks/image.html')), ('pricing', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Cennik', max_length=100)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(label='Nazwa usługi', max_length=100)), ('price', wagtail.blocks.CharBlock(label='Cena', max_length=50)), ('description', wagtail.blocks.TextBlock(label='Opis', required=False))])))])), ('gallery', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Galeria', max_length=100)), ('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))])), ('faq', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Często zadawane pytania', max_length=100)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(label='Pytanie', max_length=200)), ('answer', wagtail.blocks.RichTextBlock(label='Odpowiedź'))])))]))], blank=True, use_json_field=True)),
                ('featured_image', models.ForeignKey(blank=True, help_text='Główne zdjęcie usługi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Strona usługi',
                'verbose_name_plural': 'Strony usług',
            },
            bases=('wagtailcore.page',),
        ),
    ]
