# Generated by Django 4.2.27 on 2025-12-15 16:25

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Profesjonalne przeglądy instalacji fotowoltaicznych', max_length=200)),
                ('hero_subtitle', models.CharField(default='Zapewniamy bezpieczeństwo i maksymalną wydajność Twojej instalacji PV', max_length=300)),
                ('hero_cta_text', models.CharField(default='Zamów przegląd', max_length=50)),
                ('why_us_title', models.CharField(default='Dlaczego my?', max_length=100)),
                ('why_us_items', wagtail.fields.StreamField([('item', wagtail.blocks.StructBlock([('icon', wagtail.blocks.CharBlock(help_text="Heroicons name (e.g., 'shield-check', 'clock', 'currency-dollar')", max_length=50)), ('title', wagtail.blocks.CharBlock(max_length=100)), ('description', wagtail.blocks.TextBlock())]))], blank=True, use_json_field=True)),
                ('services_title', models.CharField(default='Nasze usługi', max_length=100)),
                ('services_subtitle', models.CharField(default='Kompleksowa obsługa instalacji OZE', max_length=200)),
                ('partners_title', models.CharField(default='Zaufali nam', max_length=100)),
                ('hero_cta_link', models.ForeignKey(blank=True, help_text='Link do strony po kliknięciu CTA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('hero_image', models.ForeignKey(blank=True, help_text='Zdjęcie w tle sekcji hero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Strona główna',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_logos', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
